---

- name: unison
  loop: "{{sync_profiles | map(attribute='profile') | list}}"
  service:
    name: "unison@{{ item }}"
    state: "{{ unison_master | default(false) | ternary('restarted', 'stopped') }}"
    enabled: "{{ unison_master | default(false) }}"

- name: daemon-reload
  command: systemctl daemon-reload
