#!/bin/sh

set -e

export HOME=/var/lib/unison
export UNISON=$HOME

check_pref () {
    if ! [ "$1" -a -r "$UNISON/$1.prf" ]
    then
        echo "Usage: $0 profilename [options]"
        echo "Profile $1 does not exist"
        exit 1
    fi
}

# use pseudo-servercmd as information via SSH_ORIGINAL_COMMAND
# to be able to pass profile name to remote unison. This *needs*
# the proper command option in the authorized_key.
if [ "$SSH_ORIGINAL_COMMAND" ] # ssh invocation by unison master
then
    eval "set -- $SSH_ORIGINAL_COMMAND"
    if [ "$1" == "unison-rsync" ]
    then
        exec "$@"
    else
        check_pref "$(echo "$1" | base64 -d)"
        shift
        exec /bin/unison "$@"
    fi
else # local systemd or shell invocation
    check_pref "$1"
    exec /bin/unison "$@" -servercmd "$(echo $1 | base64 -w0)"
fi
