---

- file: dest=/etc/unison state=directory
- copy: content={{ ed25519_sync_key }} dest=/etc/unison/id_ed25519 mode=0600
- command: sh -c "ssh-keygen -yf /etc/unison/id_ed25519 > /etc/unison/id_ed25519.pub"
- slurp: src=/etc/unison/id_ed25519.pub
  register: pubkey
- authorized_key:
    user: root
    state: present
    key: "{{ pubkey['content'] | b64decode }}"
    key_options: command="/usr/local/sbin/unison"
- file: dest=/etc/unison/id_ed25519.pub state=absent

- known_hosts:
    path: /etc/ssh/ssh_known_hosts
    name: "{{ unison_remote }}"
    key: "{{ unison_remote }} ssh-rsa {{ hostvars[unison_remote].ansible_ssh_host_key_rsa_public }}"
    state: present

- copy: src=unison.rpm dest=/tmp/unison.rpm
- yum: name=/tmp/unison.rpm disable_gpg_check=true
- command: rm -f /tmp/unison.rpm

- copy: src=unison dest=/usr/local/sbin/unison mode=0755
- copy: src=unison-rsync dest=/usr/local/sbin/unison-rsync mode=0755

- copy:
    src: unison@.service
    dest: /etc/systemd/system/unison@.service
  notify:
  - daemon-reload
  - unison

- file:
    dest: /var/lib/unison
    state: directory

- name: unison pref
  loop: "{{sync_profiles}}"
  loop_control:
    loop_var: profile
  template: dest=/var/lib/unison/{{profile.profile}}.prf src=poc.prf.j2
  notify: unison
- file: src=/var/lib/unison/{{profile.profile}}.prf dest=/etc/unison/{{profile.profile}}.prf state=link
  loop: "{{sync_profiles}}"
  loop_control:
    loop_var: profile

- file: dest={{nfs_mount_path}}/{{profile.root}} state=directory
  loop: "{{sync_profiles}}"
  loop_control:
    loop_var: profile

- sysctl:
    name: fs.inotify.max_user_watches
    value: 999999

- sysctl:
    name: fs.inotify.max_queued_events
    value: 999999

- loop: "{{sync_profiles | map(attribute='profile') | list}}"
  service:
    name: "unison@{{ item }}"
    state: "{{ unison_master | default(false) | ternary('started', 'stopped') }}"
    enabled: "{{ unison_master | default(false) }}"
